tlc.proxy.url.fetch:
    test: http://1111.ip138.com/ic.asp
    kdl: http://www.kuaidaili.com/proxylist/
    xcnn: http://www.xici.net.co/nn/
    xcnt: http://www.xici.net.co/nt/
    dl5566: http://www.daili5566.com/?stype=1&page=1
spring.profiles.active: dev
---
spring.profiles: dev
tlc.proxy.ip.localhost: 118.26.62.5
logging.config: classpath:logback-dev.xml
---
spring.profiles: test
tlc.proxy.ip.localhost: 119.29.62.227
logging.config: classpath:logback-test.xml
---
spring.profiles: prod
tlc.proxy.ip.localhost: 119.29.62.227
logging.config: classpath:logback-prod.xml